# CONFIGURACIÓN DE CONEXIÓN A MYSQL EN LA NUBE (RAILWAY)
spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:17164/paito_eventos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=KecYdiPwiwNWetaapWlTBQmQniicFgoK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE JPA / HIBERNATE
# 'validate' le dice a Spring Boot que verifique que tus futuras clases Java coincidan con las tablas que ya creaste
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Apagar Docker Compose en mi configuración
spring.docker.compose.enabled=false